### ISSUE TITLE
Add support for mocking WebSocket.bufferedAmount

### ISSUE THREAD

**Issue by marcospassos** [romgain/jest-websocket-mock#12]
First of all, thank you for sharing such a useful library!

For showing the progress of large payloads, clients usually rely on checking the property `bufferedAmount` periodically until it becomes zero. It would be useful to have a mechanism that allows mocking that behavior.

Since the property is read-only, you cannot do it currently:
```js
const connection = await server.connected;

// TS2540: Cannot assign to 'bufferedAmount' because it is a read-only property.
connection.bufferedAmount = 100;

await expect(promise).resolves.toBeUndefined();

connection.bufferedAmount = 0;

//...
```

**Comment by romgain** [comment]
Glad to hear you like this library! :)

You can work around this Typescript issue by extending the WebSocket interface:

```js
interface OverridableWS extends WebSocket {
  bufferedAmount: number;
}

const connection: OverridableWS = await server.connected;
connection.bufferedAmount = 100; // yay
```

I guess we could build this override in the library, but I'd like to avoid it unless there's a big demand for it. Currently, `server.connected` _is_ the client instance, so I'd like to keep their types consistent.


Let me know if that answers your question / fixes your issue!

**Comment by marcospassos** [comment]
Thank you for the quick reply. Setting `connection.bufferedAmount = 100` is affectless, as it's still zero afterward. For anyone else interested with the same use case, follows the workaround:

```js
const connection = await server.connected;

const bufferedAmount = jest.fn()
    .mockReturnValueOnce(20)
    .mockReturnValueOnce(10)
    .mockReturnValueOnce(0);

Object.defineProperty(connection, 'bufferedAmount', {
    get: bufferedAmount,
});
```
