### ISSUE TITLE
Use of https://github.com/YuzuJS/setImmediate

### ISSUE THREAD

**Issue by mikejw** [romgain/jest-websocket-mock#122]
I've noticed that without using the above shim for setImmediate running the web socket server from my tests produces the error `ReferenceError: setImmediate is not defined`, presumably because the test environment is jest-dom as opposed to node.  Adding this shim with `require("setimmediate");` to `setupTests.js` resolves the issue.

**Comment by romgain** [comment]
Hey @mikejw ! Thanks!

would you be willing to add this call-out at the end of the readme?

**Comment by mikejw** [comment]
Sure!

**Comment by mikejw** [comment]
https://github.com/romgain/jest-websocket-mock/pull/123
