### ISSUE TITLE
Refuse connections

### ISSUE THREAD

**Issue by marcospassos** [romgain/jest-websocket-mock#13]
We have a use case where we have to test that a client automatically reconnects (within a max number of attempts) to the server after the server has closed the connection. 

Is there any way to refuse connections currently?

**Comment by romgain** [comment]
Hi @marcospassos !

I added event listeners to the server object, so you can now add custom logic when clients connect.

I believe that https://github.com/romgain/jest-websocket-mock/commit/f6a3c2de3152a9f9ef48667768bef90093167eea does what you need, but please let me know if that's not the case :slightly_smiling_face:

**Comment by marcospassos** [comment]
@romgain, thank you for accepting the suggestion. Any chances of releasing a new version with the latest fixes and features?

**Comment by romgain** [comment]
v1.5.0 is now available on npm :slightly_smiling_face:
