### ISSUE TITLE
Reconnection always fails after an error

### ISSUE THREAD

**Issue by marcospassos** [romgain/jest-websocket-mock#15]
Trying to reconnect after an error always fails. It's particularly useful for testing auto-reconnect mechanisms.

```js
const server = new WS('ws://localhost:8080');

new WebSocket('ws://localhost:8080');
await server.connected;
server.close();
await server.closed;

// Fails
new WebSocket('ws://localhost:8080');
await server.connected;
```

**Comment by romgain** [comment]
Good catch!

I didn't realise that mock-socket's `stop` method actually unregistered the global WebSocket mock...
