### ISSUE TITLE
ArrayBuffer & Binary messages?

### ISSUE THREAD

**Issue by luchillo17** [romgain/jest-websocket-mock#159]
I'm trying to test an XTerm web shell that makes use of [channel.k8s.io](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/httpstream/wsstream#ChannelWebSocketProtocol) subprotocol for the WebSocket, basically the messages are ArrayBuffers, and I have issues using this library to mock the server since I don't see an option to send ArrayBuffer or Binary data.

Is there an undocumented way or is just not supported?

**Comment by zmb3** [comment]
FWIW, it seems to work fine for me if I `send` an ArrayBuffer instead of a raw array.

```
ws.send(new ArrayBuffer(...
```

**Comment by luchillo17** [comment]
I worked around whatever the issue is and I'm not in the project anymore, closing this.
