### ISSUE TITLE
Undefined WebSocket.bufferedAmount

### ISSUE THREAD

**Issue by marcospassos** [romgain/jest-websocket-mock#16]
The `WebSocket.bufferedAmount` should not be undefined but zero:

```js
const server = new WS('ws://localhost:8080');
new WebSocket('ws://localhost:8080');
const connection = await server.connected;

// Outputs undefined
console.log(connection.bufferedAmount);
```

**Comment by romgain** [comment]
Hi @marcospassos !
This is an issue with https://github.com/thoov/mock-socket, the library we use for mocking out websocket connections. Would you mind opening this on their bug tracker?

**Comment by marcospassos** [comment]
Done: https://github.com/thoov/mock-socket/issues/266

**Comment by romgain** [comment]
Thanks!
