### ISSUE TITLE
TS: typedef for toReceiveMessage is wrong

### ISSUE THREAD

**Issue by neezer** [romgain/jest-websocket-mock#19]
The [`toReceiveMessage` matcher is `async`](https://github.com/romgain/jest-websocket-mock/blob/43c09b9f4c9d059cb1c49bc43721f757fffb854d/src/matchers.ts#L40), but [the exported signature is not](https://github.com/romgain/jest-websocket-mock/blob/43c09b9f4c9d059cb1c49bc43721f757fffb854d/src/matchers.ts#L8-L10).

Thus TS complains:

<img width="770" alt="Screen Shot 2019-10-11 at 2 20 35 PM" src="https://user-images.githubusercontent.com/29997/66685900-9c851c80-ec32-11e9-9343-a090331a95cc.png">

Should be defined as [an async matcher](https://jestjs.io/docs/en/expect#async-matchers).

**Comment by romgain** [comment]
Hi @neezer !

Thanks for reporting this!
I'm sure you're right, but I can't reproduce this. Would you mind sharing a small repo where this issue can be reproduced so that I can add some automated testing to make sure this doesn't happen again?

**Comment by neezer** [comment]
@romgain Here's the smallest repo I could think to make: https://github.com/neezer/jest-websocket-mock-test

Included is `vscode-info.txt`, which has my VSCode version information, and a screenshot of the same error (like above), but for the example repo.

**Comment by romgain** [comment]
Thank you very much for setting up that repro!

It looks like this warning comes directly from VS Code? Please let me know if you know what it's using under the hood to detect this - I'd love to add testing around this to make sure this doesn't happen again.

**Comment by romgain** [comment]
@neezer It should now be fixed in v1.5.1 - let me know if you have any other issues!

**Comment by neezer** [comment]
> Please let me know if you know what it's using under the hood to detect this

Not sure, but I do know that VSCode uses TypeScript, so at some level it's a TS warning. Looks like this warning in particular was added with this PR: https://github.com/microsoft/TypeScript/pull/32384

I'll give the new version a try in a bit and report back.
