### ISSUE TITLE
Consider supporting connection delays

### ISSUE THREAD

**Issue by marcospassos** [romgain/jest-websocket-mock#31]
It would be nice to have an option that delays connections so we can mock connection timeouts and catch cases where the `readyState` is `CONNECTING`.

```js
const server = new WS("ws://localhost:1234", {delay: 10000});

expect(client.readyState).toBe(WebSocket.CONNECTING);

// 10 seconds later...
await server.connected;
```

**Comment by romgain** [comment]
Hi @marcospassos ! 

What exactly are you trying to test?

When testing connection timeouts, it's usually better to mock timers rather than artificially introduce delays, as they can make tests slow and flakey.

**Comment by romgain** [comment]
Hi @marcospassos !

I think that a graceful solution for this could be to add a `autoConnect` option to `WSOptions` in the constructor that defaults to `true`.

We could then move this block to a separate `connect` function: https://github.com/romgain/jest-websocket-mock/blob/master/src/websocket.ts#L48-L60 , that would be called automatically when `autoConnect` is true.

You're use case would then be achieved like this:

```ts
const server = new WS("ws://localhost:1234", { autoConnect: false });

expect(client.readyState).toBe(WebSocket.CONNECTING);

setTimeout(() => server.connect(), 10000);

// 10 seconds later...
await server.connected;
```

What do you think?


Would you be open to sending a PR that adds this?

**Comment by romgain** [comment]
Closing for now, but feel free to reopen if you have more feedback/questions!
