### ISSUE TITLE
WebSocket onclose callback is invoked multiple time with wrong readyState code

### ISSUE THREAD

**Issue by svh2811** [romgain/jest-websocket-mock#33]
I am executing this test case

```
test("WebSocket Close", async () => {
    const server = new WS("wss://localhost:1234");
    let ws = new WebSocket("wss://localhost:1234");
    ws.addEventListener("open", () => console.log("WS OPEN"));
    ws.addEventListener("error", () => console.log("WS ERROR"));
    ws.addEventListener("close", () => {
        console.log("WS CLOSE : " + ws.readyState)
    });
    await server.connected; // wait for the server to have established the connection
    server.close(); // Gracefully close the connection
    await server.closed;
})
```

Console Outputs were as follows

```
WebSocket Close (33ms)

console.log test/web-socket.spec.js:277
  WS OPEN

console.log test/web-socket.spec.js:280
  WS CLOSE : 1

console.log test/web-socket.spec.js:280
  WS CLOSE : undefined
```

`close` callback should have been invoked only once and with readyState 3 (as stated [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Constants)) 

Same behaviour is observed even when I replace addEventListener with callback assignment 
```
test("WebSocket Close", async () => {
    const server = new WS("wss://localhost:1234");
    let ws = new WebSocket("wss://localhost:1234");
    ws.onopen = () => console.log("WS OPEN");
    ws.onerror = () => console.log("WS ERROR");
    ws.onclose = () => console.log("WS CLOSE : " + ws.readyState);
    await server.connected; // wait for the server to have established the connection
    server.close(); // Gracefully close the connection
    await server.closed;
})
```

**Comment by romgain** [comment]
Hi @svh2811 !

Unfortunately, the `readyState` issue is a bug with mock-socket, the library we use to mock out webscoket servers. See https://github.com/romgain/jest-websocket-mock/issues/14 and https://github.com/thoov/mock-socket/issues/267 for more details. 

I have fixed the issue with the `close` callback being called twice here: https://github.com/romgain/jest-websocket-mock/commit/28dd2b83d797d11ca1b4f5dea17d50b1032a9691, and will be releasing this in a new version shortly.


Thanks!

**Comment by romgain** [comment]
Feel free to reopen if that's still an issue!
