### ISSUE TITLE
Message Event on Server not working

### ISSUE THREAD

**Issue by sp1r1t** [romgain/jest-websocket-mock#38]
Hi @romgain ,
It seems to me, that the on message event is not working. I created the code below based on your examples in the readme.
Because of console.log in server.on('message'), I would expect to see an output, when the client sends a message, but that does not happen.
To ensure events are working, I added the server.on('connection'), which does it's job perfectly.
Also the server.nextMessage promise works like described. Also the client message is obviously received by the server, as the test passes.

Is this a user error or a bug?

Best regards

``` js
test("the server keeps track of received messages, and yields them as they come in", async () => {
	const server = new WS("ws://localhost:1234");
	server.on('connection', socket => {
		console.log(`server got event connection`);
	});
	server.on('message', msg => {
		console.log(msg);
	});

	const client = new WebSocket("ws://localhost:1234");
	client.onmessage = msg => {
		console.log(msg.data);
	};

	await server.connected;

	server.send('server says hi');
	client.send('client says hi');

	await expect(server).toReceiveMessage('client says hi');
	expect(server).toHaveReceivedMessages(['client says hi']);
});
```

Output:
```
  ✓ the server keeps track of received messages, and yields them as they come in (31ms)

  console.log test/100_ws.mod.test.js:63
    server got event connection

  console.log test/100_ws.mod.test.js:71
    server says hi

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.79s, estimated 1s
```

**Comment by romgain** [comment]
Hi @sp1r1t !

The `message` events are actually triggered on the socket instance, not the server. See https://github.com/romgain/jest-websocket-mock/commit/b44dd17ab121ed13a647c299944c7c8e06eea99a for an example!


I hope that answers your question!


Feel free to re-open this if you have more questions! :slightly_smiling_face:

**Comment by trickeyd** [comment]
Thanks @romgain - this had me stumped too
