### ISSUE TITLE
Rename `close` method to `tearDown`

### ISSUE THREAD

**Issue by G-Rath** [romgain/jest-websocket-mock#4]
The `close` method would be better suited as as `tearDown`.

This is b/c it calls `server.stop`, which removes the `WebSocket` reference.

This means the proper way to test close functionality is like so:

```
it('emits a "Close" event', () => {
  clientSocket.addListener(BSClientSocketEvent.Close, listener);

  ws.server.close({
    code: 3001,
    reason: 'no reason',
    wasClean: true
  });

  const expected: BSClientSocket.CloseEvent = {
    disconnectCode: 3001
  };

  expect(listener).toHaveBeenCalledTimes(1);
  expect(listener).toHaveBeenCalledWith(expected);
});
```

Meanwhile, `WS#close` should be used to clean up everything without having to worry about the details, such as in an `afterEach` block.

The `emit` should probably be removed too, since `server.close` already emits the proper `close` event.

**Comment by G-Rath** [comment]
@romgain let me know if I've missed anything out. And don't forget to add a `Breaking Change` tag.

Also, let me know if you'd be happy to alias the method - if so, I'll whip a PR 😄

**Comment by romgain** [comment]
That's great, thanks!
Let's hold on until there are more breaking changes before raising a PR, that way we won't have to deal with potential merge conflicts!

**Comment by romgain** [comment]
Closing for now - I think it would be worth considering more api changes for the next major release! :slightly_smiling_face:
