### ISSUE TITLE
Jest - Async Callback timeout with Example Tests

### ISSUE THREAD

**Issue by jpowell96** [romgain/jest-websocket-mock#42]
### Issue: 
When following the example of initializing the server in 'beforeEach' and calling WS.clean() in 'afterEach', the provided example tests fail with an Async Callback timeout:

>  Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

I'm attempting to use 'jest-websocket-mock' in a project I'm working on. Before using the library, I'm trying to run the example tests provided. In the example below, I use the suggested setup and teardown logic from the documentation, and apply it to one of the example tests. The test fails with an Async Callback Timeout. 

Is there any guidance on how I should modify the test?
```javascript
import WS from "jest-websocket-mock";

describe("Testing Jest Websocket Mock", () => {
  let  server : WS;
  beforeEach(async () => {
    server = new WS("ws://localhost:1234");
    await server.connected;
  });

  afterEach(() => {
    WS.clean();
  });



  test("the server keeps track of received messages, and yields them as they come in", async () => {
    const client = new WebSocket("ws://localhost:1234");
       client.send("hello");
    await expect(server).toReceiveMessage("hello");
    expect(server).toHaveReceivedMessages(["hello"]);
  });

});
```

However, when I remove the 'beforeEach' and 'afterEach', and move the server logic into the test itself, the test passes.

**Comment by romgain** [comment]
Hi @jpowell96 !

Thanks for reporting this, it's indeed an issue with the docs.

We need to actually connect to the server before awaiting `server.connected`. In your example, that means moving the `await server.connected` statement in the `test` block, after the `WebSocket` instanciation:


```ts
describe("Testing Jest Websocket Mock", () => {
  let server: WS;
  beforeEach(async () => {
    server = new WS("ws://localhost:1234");
  });

  afterEach(() => {
    WS.clean();
  });

  test("the server keeps track of received messages, and yields them as they come in", async () => {
    const client = new WebSocket("ws://localhost:1234");
    await server.connected;
    client.send("hello");
    await expect(server).toReceiveMessage("hello");
    expect(server).toHaveReceivedMessages(["hello"]);
  });
});
```


Or, alternatively, instanciate a shared client instance:

```ts
describe("Testing Jest Websocket Mock", () => {
  let server: WS, client: WebSocket;
  beforeEach(async () => {
    server = new WS("ws://localhost:1234");
    client = new WebSocket("ws://localhost:1234");
    await server.connected;
  });

  afterEach(() => {
    WS.clean();
  });

  test("the server keeps track of received messages, and yields them as they come in", async () => {
    client.send("hello");
    await expect(server).toReceiveMessage("hello");
    expect(server).toHaveReceivedMessages(["hello"]);
  });
});
```

**Comment by jpowell96** [comment]
Ahhh, that makes sense. Thank you for pointing that out!

**Comment by romgain** [comment]
NP, feel free to re-open if you have more issues!
