### ISSUE TITLE
Reconnection logic / Empty `closedResolver`

### ISSUE THREAD

**Issue by loxy** [romgain/jest-websocket-mock#44]
Hi!

I try to test some reconnection logic. So I'm basically doing something like this:

```ts
server.close({ code: 1001, reason: "Something went wrong!", wasClean: true });
await server.closed;
await server.connected;  // problematic...
```

But it seems that the connection is not "cleaned up" after a close. The `closedResolver` is doing nothing: `closedResolver!: () => void;`. So, the last line in my code seems to be always true (I think from the first "connection"), because the open event is not fired again. Is it possible to alter the `closedResolver` somehow? Or did I oversee something?

Great library, btw! 

Best regards,
Kersten

**Comment by romgain** [comment]
Hi Kersten!

Thanks for raising this!

Could you share a small unit test that reproduces the issue you're seeing?


Thanks!

**Comment by loxy** [comment]
Yes, but I'm relying on `WebSocketSubject` from RxJS. Can try to eliminate this...

**Comment by romgain** [comment]
It would definitely be easier to troubleshoot if you can share a small reproducer without rxjs.

Otherwise, might be interesting to add an rxjs example [here](https://github.com/romgain/jest-websocket-mock/tree/master/examples) if you're up for it :slightly_smiling_face:

**Comment by loxy** [comment]
Ok, something like this:

```ts
  it('should work', async () => {
    // arrange
    const url = 'ws://fake:1234';
    const server = new WS(url);
    let client = new WebSocket(url);
    const open = jest.fn();
    const close = jest.fn();
    client.onopen = open;
    client.onclose = close;
    await server.connected;

    // act
    server.close({ code: 1001, reason: 'Something went wrong!', wasClean: true });
    await server.closed;
    client = new WebSocket(url);
    client.onopen = open;
    client.onclose = close;
    await server.connected;

    // assert
    expect(close).toHaveBeenCalledTimes(1);
    expect(open).toHaveBeenCalledTimes(2);
  });
```

I can add a example. But it is straight forward...

**Comment by romgain** [comment]
Thanks for sharing that - definitely a bug.

I think your test should close the client though, not the server, as the new client websocket will never be able to connect to a closed server :-)

**Comment by loxy** [comment]
That makes sense. But in reality not the server is closed but the connection. And my code is all about to try to reconnect on a close from the server

**Comment by romgain** [comment]
Hmmm, unfortunately, once you've closed the `mock-socket`, you need to re-instantiate it if you want it to start accepting connections again...

**Comment by romgain** [comment]
I think this will solve your issue though: https://github.com/romgain/jest-websocket-mock/pull/45

Let me know what you think

**Comment by loxy** [comment]
What a pity! But your code looks good to me. Hopefully it will work for me.
Thank you for your effort!

**Comment by romgain** [comment]
That ended up breaking a few tests that I think should still pass...

In the end, I'm afraid that the best solution is to restart the server when you're ready for it to start accepting connections again.
I force pushed an example to https://github.com/romgain/jest-websocket-mock/pull/45 - let me know what you think.

**Comment by loxy** [comment]
This doesn't work for me. Because when the server closes, the client immediately tries to reconnect. So my `client = new WebSocket("ws://localhost:1234");` is before `server = new WS("ws://localhost:1234");`. Therefore I get an error and a time out from Jest. But don't worry, I will make the test a little bit less verbose and will only check if the reconnect method is called on my site.

**Comment by romgain** [comment]
That's unfortunate.

I tried a couple other  things, but nothing that really works if you try to reconnect _immediately_ in the `onclose` websocket callback.

Do you have any reconnection timeouts you could mock and manually trigger?
Also, what happens if your first reconnection attempt times out / fails? Does it retry again? If so, would it make sense to exercise this logic in your tests.


In any case, I'd be happy to review any PRs that would make it work for you :slightly_smiling_face:

**Comment by romgain** [comment]
I'll close this for now, but feel free to reopen if you have any suggestions!

**Comment by loxy** [comment]
Oh sorry for the delay, Romain. I've circumnavigated the problem somehow. It is not ideal, but for the tests ok. Thank you for your patience!
