### ISSUE TITLE
require error

### ISSUE THREAD

**Issue by L924553229** [romgain/jest-websocket-mock#65]
When using the library, that is something along;

Example:

const WS = require('jest-websocket-mock');

Uncaught ReferenceError: expect is not defined

**Comment by romgain** [comment]
Hey @L924553229 !

It looks like you might just need to install `jest`?

I think that's the issue, so I'll close this for now, but please feel free to re-open with a link to a repo that reproduces the issue if there's still a problem!


Thank you!
