### ISSUE TITLE
server.connected and server.closed are usable only for the first connection

### ISSUE THREAD

**Issue by kraus-milan** [romgain/jest-websocket-mock#66]
`server.connected` is resolved on first connection and when connection is closed and re-opened again, it doesn't work properly.
The same goes for `server.closed`.

Example:

```
const server = new WS("ws://localhost:1234");

let totalConnections = 0;

server.on("connection", () => {
  totalConnections++;
});

const clientOne = new WebSocket("ws://localhost:1234");

await server.connected;

expect(totalConnections).toBe(1); // OK

clientOne.close();

await server.closed;

const clientTwo = new WebSocket("ws://localhost:1234");

await server.connected;

expect(totalConnections).toBe(2); // ERROR
```

**Comment by aelhage** [comment]
Were you able figure out a supported way to wait for a second connection? For my use case I am able to stop and recreate the server, but these seems a bit clumsy:
`ws.server.stop(() => (ws = new WS(DEFAULT_WEBSOCKET_HOST)));`
