### ISSUE TITLE
Use optional generics in expect matchers

### ISSUE THREAD

**Issue by G-Rath** [romgain/jest-websocket-mock#7]
This is change I've suggested for the actual [`jest` typings](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34522) as well.

Basically, if you defined your matchers with generics, it'll let us explicitly denote the expected type, and benefit from both autocompletion & strong typing:

```
toReceiveMessage<TMessage = object>(message: DeserializedMessage<TMessage>): R;
toHaveReceivedMessages<TMessage = object>(messages: Array<DeserializedMessage<TMessage>>): R;
```

This would result in `DeserializedMessage` becoming generic as well:

```
export type DeserializedMessage<TMessage = object> = string | TMessage;
```

Use case:

<img width="451" alt="ss+(2019-04-06+at+11 14 41)" src="https://user-images.githubusercontent.com/3151613/55668142-ccd5b200-58c1-11e9-8a93-2877c84c14f4.png">

```
it('sends the message', () => {
  const requestType: BotSocket.RequestType = 'handshake';
  const requestData: BotSocket.ClientHandshakeData = {
    userId: 'client-1'
  };

  clientSocket.sendMessageToServer(requestType, requestData);

  expect(ws).toHaveReceivedMessages<BotSocket.Message>([
    {
      request: 'handshake',
      data: {
        userId: 'hello world'
      }
    }
  ]);
});
```

I'm happy to make a PR if you're happy to merge it 😄

**Comment by romgain** [comment]
Oh that's interesting!
As long as that's 100% backwards compatible I'd be happy to merge a PR implementing this :slightly_smiling_face:

**Comment by G-Rath** [comment]
Thats the hope! This should serve as a good test case regardless 😝

I'll whip up a PR
