### ISSUE TITLE
Jenkins build failure after upgrade to v2.3.0

### ISSUE THREAD

**Issue by sorinpav** [romgain/jest-websocket-mock#70]
Hello! 

I have upgraded jest-websocket-mock to v2.3.0 from v2.2.1 and my Jenkins CI build started failing because of a test that's making use of jest-websocket-mock. 

This is the error I'm getting: 
![image](https://user-images.githubusercontent.com/50046459/152850367-5aa86e3b-bd29-4f55-a86d-a0a11a9fe14a.png)

Worth noting that this issue is **only happening on Jenkins, not locally**. 

What's strange is that the changelog does not appear to mention any breaking changes. 

Have I missed any migration guides or anything? 

If you need more details, please let me know.

Any help is appreciated, thank you!

**Comment by romgain** [comment]
Hey @sorinpav !

It looks like your Jenkins is running a Node version that doesn’t support optional chaining?
Can you try with Node.js 14 or more recent?

Apologies, this definitely slipped through the release notes…

**Comment by sorinpav** [comment]
Thanks for the answer! No worries, will try to update the node version on Jenkins and I will update on here. Not sure how long this would take, as there are other things that may need to happen first.

It might be best if you could update your release notes, though, to avoid confusion in the future. Thank you!

**Comment by romgain** [comment]
Thanks @sorinpav !

I have now updated the release notes 😊

**Comment by romgain** [comment]
I’ll close this for now, but please reopen this issue if updating node doesn’t fix the issue!
